Vagrant.configure(2) do |config|
  config.vm.box = "centos7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "../server", "/var/www/server", create:true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
